DELETE http://localhost:3001/api/blogs/65edea3e3b5e47f78abd98ea
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5pdCIsImlkIjoiNjVlZGNmMTFmNTg0NGIwYjA0YTYwZDFiIiwiaWF0IjoxNzEwMDkwNjE1fQ.QhvAGvYYrMK1xx75aFIn7xIKvw2jai6tLma2vCvH4Nc