DELETE http://localhost:3001/api/blogs/65edcf17f5844b0b04a60d22
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5pdCIsImlkIjoiNjVlZGNmMTFmNTg0NGIwYjA0YTYwZDFiIiwiaWF0IjoxNzEwMDkwNjE1fQ.QhvAGvYYrMK1xx75aFIn7xIKvw2jai6tLma2vCvH4Nc